heat_template_version: rocky

description: Example template for the monitoring VM

parameters:
  ssh_keys:
    type: comma_delimited_list

resources:

  monitor_port:
    type: OS::Neutron::Port
    properties:
      network_id: private_net
      security_groups: [ ssh_security_group, internal_security_group]
      fixed_ips:
        - subnet_id: private_subnet
          ip_address: 192.168.10.11

  monitor:
    type: vm-template.yaml
    properties:
      name: monitor
      flavor: s10.medium 
      network_port: { get_resource: monitor_port}
      ssh_keys: {get_param: ssh_keys}
