heat_template_version: rocky

description: One template for the six Vms for Kubernetes. These servers must be unreachable from outside the OpenStack infrastructure but must be able to communicate on all TCP/UDP ports with all the other VMs of your group.

parameters:

  protocols:
    type: comma_delimited_list
    label: protocols
    default: "tcp,udp"
resources:
  
  k_internal_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Open all the ports inside the private network"
      name: k_internal_security_group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          repeat:
            for_each:
              <%protocol%>: { get_param: protocols }
              template:
                protocol: <%protocol%>
                
  
  k_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_resource: private_net}
      security_groups: [ get_resource: k_internal_security_group]
             
          
  kub_server1:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}

  kub_server2:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}
  kub_server3:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}
  kub_server4:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}

  kub_server5:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}
  
  kub_server6:
    type: vm-template.yaml
    properties:
      name: k_bastion
      flavor: s10.medium
      network_port: { get_resource: k_port}




      
      
  
